source "https://rubygems.org"

ruby "~> 3.2"

gem "rails", "~> 8.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.0"
gem "good_job", "~> 4.0"
gem "bootsnap", ">= 1.4.4", require: false
gem "phlex-rails", "~> 2.3"
gem "style_capsule", "~> 1.4"
gem "turbo-rails"

group :development, :test do
  gem "rspec-rails"
  gem "pry"
end


gem "importmap-rails", "~> 2.2"

gem "propshaft", "~> 1.3"
gem "tailwindcss-rails", "~> 2.0"
